ARG version
FROM almalinux:${version:-8}
ARG COURSE=Docker
ARG Trainer=sivakumar
ARG Duration=120hrs
ENV Duration=${Duration}
ENV laptop=thinkpad
RUN echo "course is ${COURSE} and trainer is ${Trainer} on laptop is ${laptop}"
CMD [ "sleep","100" ]